version: '3.7'

services:

  webapi:
    image: webapi
    depends_on:
      - "redis_cache"
    build:
      context: .
      dockerfile: DistributedLockExample.WebApi/Dockerfile
    ports:
      - "5119:5119"
    links:
      - "redis_cache"
    environment:
      - ASPNETCORE_URLS=http://+:5119

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
